title: Francisco "Bobby" Soto
author: Francisco "Bobby" Soto

url: "https://ebobby.org"

footer_only_homepage: true

profile-picture: assets/profile.png
favicon_location: favicon.png

permalink: /:year/:month/:day/:title/

collections:
  poems:
    output: true
    permalink: /:collection/:name

plugins:
  - jekyll-feed
