title: Francisco Soto
author: Francisco Soto

url: "https://ebobby.org"

footer_only_homepage: true

profile-picture: assets/profile.png
favicon_location: favicon.png

permalink: /:year/:month/:day/:title/

plugins:
  - jekyll-feed
