title: Francisco Soto
author: Francisco Soto

url: "https://blog.ebobby.org"
paginate: 10

footer_only_homepage: true
footer_url: "https://github.com/pro-panda"
footer_text: "Theme by pro-panda"

profile-picture: assets/profile.png
favicon_location: assets/favicon.png

permalink: /:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

navbar:
 - name: "Resume"
   absolute-link: "https://ebobby.org/resume.pdf"
 - name: "About"
   absolute-link: "https://ebobby.org"
