title: Francisco Soto
author: Francisco Soto

url: "https://ebobby.org"
paginate_path: "/blog/page:num/"
paginate: 6

footer_only_homepage: true

profile-picture: assets/profile.png
favicon_location: assets/favicon.png

permalink: /:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

navbar:
 - name: "Resume"
   absolute-link: "/resume.pdf"
 - name: "About"
   absolute-link: "/"
